sudo : required 
services: 
 - docker

 before_install :
  - docker-build -t gulliver2019/docker-react-f DOckerfile.dev .

  script:
  - docker run gulliver2019/docker-react npm run test -- --coverage